# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs\gui_fit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(505, 642)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cbModel = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbModel.sizePolicy().hasHeightForWidth())
        self.cbModel.setSizePolicy(sizePolicy)
        self.cbModel.setObjectName("cbModel")
        self.verticalLayout.addWidget(self.cbModel)
        self.cbCustom = QtWidgets.QCheckBox(Form)
        self.cbCustom.setObjectName("cbCustom")
        self.verticalLayout.addWidget(self.cbCustom)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.cbMethod = QtWidgets.QComboBox(Form)
        self.cbMethod.setObjectName("cbMethod")
        self.verticalLayout.addWidget(self.cbMethod)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pteEquation = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteEquation.sizePolicy().hasHeightForWidth())
        self.pteEquation.setSizePolicy(sizePolicy)
        self.pteEquation.setMinimumSize(QtCore.QSize(0, 70))
        self.pteEquation.setMaximumSize(QtCore.QSize(16777215, 300))
        self.pteEquation.setPlainText("")
        self.pteEquation.setObjectName("pteEquation")
        self.verticalLayout.addWidget(self.pteEquation)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.leX0 = MyLineEdit(Form)
        self.leX0.setObjectName("leX0")
        self.horizontalLayout.addWidget(self.leX0)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.leX1 = MyLineEdit(Form)
        self.leX1.setObjectName("leX1")
        self.horizontalLayout.addWidget(self.leX1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.sbParamsCount = QtWidgets.QSpinBox(Form)
        self.sbParamsCount.setMinimum(1)
        self.sbParamsCount.setMaximum(10)
        self.sbParamsCount.setObjectName("sbParamsCount")
        self.horizontalLayout.addWidget(self.sbParamsCount)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.cbUpdateInitValues = QtWidgets.QCheckBox(Form)
        self.cbUpdateInitValues.setObjectName("cbUpdateInitValues")
        self.verticalLayout.addWidget(self.cbUpdateInitValues)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbPropWeighting = QtWidgets.QCheckBox(Form)
        self.cbPropWeighting.setChecked(False)
        self.cbPropWeighting.setObjectName("cbPropWeighting")
        self.horizontalLayout_2.addWidget(self.cbPropWeighting)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnPrintReport = QtWidgets.QPushButton(Form)
        self.btnPrintReport.setCheckable(False)
        self.btnPrintReport.setChecked(False)
        self.btnPrintReport.setAutoRepeat(False)
        self.btnPrintReport.setAutoDefault(False)
        self.btnPrintReport.setObjectName("btnPrintReport")
        self.gridLayout_2.addWidget(self.btnPrintReport, 1, 1, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(Form)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_2.addWidget(self.btnCancel, 1, 4, 1, 1)
        self.btnPlotFunction = QtWidgets.QPushButton(Form)
        self.btnPlotFunction.setCheckable(False)
        self.btnPlotFunction.setChecked(False)
        self.btnPlotFunction.setAutoRepeat(False)
        self.btnPlotFunction.setAutoDefault(False)
        self.btnPlotFunction.setObjectName("btnPlotFunction")
        self.gridLayout_2.addWidget(self.btnPlotFunction, 0, 0, 1, 1)
        self.btnFit = QtWidgets.QPushButton(Form)
        self.btnFit.setCheckable(False)
        self.btnFit.setChecked(False)
        self.btnFit.setAutoRepeat(False)
        self.btnFit.setAutoDefault(False)
        self.btnFit.setObjectName("btnFit")
        self.gridLayout_2.addWidget(self.btnFit, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.btnOK = QtWidgets.QPushButton(Form)
        self.btnOK.setAutoDefault(False)
        self.btnOK.setObjectName("btnOK")
        self.gridLayout_2.addWidget(self.btnOK, 0, 4, 1, 1)
        self.btnClearPlot = QtWidgets.QPushButton(Form)
        self.btnClearPlot.setCheckable(False)
        self.btnClearPlot.setChecked(False)
        self.btnClearPlot.setAutoRepeat(False)
        self.btnClearPlot.setAutoDefault(False)
        self.btnClearPlot.setObjectName("btnClearPlot")
        self.gridLayout_2.addWidget(self.btnClearPlot, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Model:"))
        self.cbCustom.setText(_translate("Form", "Custom model (equation window will be editable)"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p>Minimizing algorithm:</p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">def func(x, *params):</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "Selected x range:"))
        self.label_11.setText(_translate("Form", "from"))
        self.label_12.setText(_translate("Form", "to"))
        self.label_9.setText(_translate("Form", "Params"))
        self.cbUpdateInitValues.setText(_translate("Form", "Update initial values when linear region move is finished"))
        self.cbPropWeighting.setText(_translate("Form", "Proportional weighting"))
        self.label_14.setText(_translate("Form", "e<sub>i</sub>*=1/y<sub>i</sub><sup>2</sup>"))
        self.label_7.setText(_translate("Form", "Fixed"))
        self.label_3.setText(_translate("Form", "Param"))
        self.label_8.setText(_translate("Form", "Error"))
        self.label_6.setText(_translate("Form", "Upper\n"
"bound"))
        self.label_4.setText(_translate("Form", "Lower\n"
"bound"))
        self.label_5.setText(_translate("Form", "<= Value <="))
        self.btnPrintReport.setText(_translate("Form", "Print report"))
        self.btnCancel.setText(_translate("Form", "Cancel"))
        self.btnPlotFunction.setText(_translate("Form", "Plot Function"))
        self.btnFit.setText(_translate("Form", "Fit"))
        self.btnOK.setText(_translate("Form", "Ok"))
        self.btnClearPlot.setText(_translate("Form", "Clear Plot"))
from dialogs.mylineedit import MyLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
